# Generated by Django 5.1.15 on 2026-09-21 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('en_proceso', 'En proceso'), ('resultada', 'Con resultados'), ('validada', 'Validada'), ('pdf', 'PDF generado'), ('entregada', 'Entregada')], default='registrada', max_length=20)),
                ('solicitado_por', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('medicion', models.CharField(choices=[('unica', 'Unica'), ('pre', 'Pre'), ('post', 'Post')], default='unica', max_length=10)),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('bandera', models.CharField(blank=True, max_length=5)),
                ('importado_de', models.CharField(blank=True, max_length=50)),
                ('validado_at', models.DateTimeField(blank=True, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.examen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.orden')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.paquete')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'item de orden',
                'verbose_name_plural': 'items de orden',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
