# Generated by Django 5.1.15 on 2026-09-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('clinica', 'Clinica / Consultorio'), ('dialisis', 'Centro de dialisis')], default='clinica', max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('sangre', 'Sangre'), ('aguas', 'Aguas')], default='sangre', max_length=10)),
                ('resultado_tipo', models.CharField(choices=[('numerico', 'Numerico'), ('texto', 'Texto')], default='numerico', max_length=10)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('metodo', models.CharField(blank=True, max_length=100)),
                ('ref_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ref_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ref_texto', models.CharField(blank=True, max_length=200)),
                ('mide_pre_post', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'examen',
                'verbose_name_plural': 'examenes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('frecuencia', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='TarifarioPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifarios', to='catalogo.paquete')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.zona')),
            ],
            options={
                'verbose_name': 'tarifa de paquete',
                'verbose_name_plural': 'tarifas de paquete',
                'ordering': ['paquete', 'precio'],
            },
        ),
        migrations.CreateModel(
            name='TarifarioExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.cliente')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifarios', to='catalogo.examen')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.zona')),
            ],
            options={
                'verbose_name': 'tarifa de examen',
                'verbose_name_plural': 'tarifas de examen',
                'ordering': ['examen', 'precio'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.zona'),
        ),
        migrations.CreateModel(
            name='PaqueteExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_compuestos', to='catalogo.examen')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_compuestos', to='catalogo.paquete')),
            ],
            options={
                'verbose_name': 'examen del paquete',
                'verbose_name_plural': 'examenes del paquete',
                'ordering': ['paquete', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('paquete', 'examen'), name='uk_paquete_examen')],
            },
        ),
    ]
