# Generated by Django 5.1.15 on 2026-09-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['nombre'], 'verbose_name': 'zona', 'verbose_name_plural': 'zonas'},
        ),
    ]
