# Generated by Django 5.1.15 on 2026-09-21 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('pdf', models.FileField(blank=True, upload_to='reportes/%Y/%m')),
                ('codigo_qr', models.CharField(blank=True, max_length=200)),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('enviado_a', models.EmailField(blank=True, max_length=254)),
                ('entregado_at', models.DateTimeField(blank=True, null=True)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_entregados', to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='ordenes.orden')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['-generado'],
            },
        ),
    ]
